version: "3.7"

services:
  postgres-compose:
    image: postgres:12.4-alpine
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5440:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - network

#  pgadmin-compose:
#    image: dpage/pgadmin4
#    container_name: pgadmin
#    environment:
#      PGADMIN_DEFAULT_EMAIL: "example@example.com"
#      PGADMIN_DEFAULT_PASSWORD: "pgadmin1234"
#    ports:
#      - "15432:80"
#    depends_on:
#      - postgres-compose
#    networks:
#      - network

networks:
  network:
    driver: bridge

volumes:
  postgres-data:
    external: true